name: fastbldr
version: '${project.version}'
main: fastbldr.fastbldr.fastbldr
api-version: 1.19
authors: [ rye ]
depend: [WorldEdit, WorldGuard]
description: sets up/manages fastbuilder gamemode
commands:
  reloadconfig:
    description: reload fastbuilder config
    usage: /<command>
  debugfunction:
    description: debugs function
    usage: /<command>
  troll:
    description: trolls specified player
    usage: /<command> <player>