name: fastbldr
version: '${project.version}'
main: fastbldr.fastbldr.fastbldr
api-version: 1.19
authors: [ rye ]
depend: [WorldEdit]
description: sets up/manages fastbuilder gamemode
commands:
  updatefbschem:
    description: updates fastbuilder schematic
    usage: /<command> <schem file> <build length> <start position> <player position>
  debugfunction:
    description: debugs function
    usage: /<command>